### PR TITLE
Fix for ACS tracker

### PR DESCRIPTION
**Pull request by DanielPikilidis**
With the use of Selenium I managed to kinda fix this. It's not great and it's pretty slow but it works. 

I also added all the dependencies in the requirements.txt. I didn't do any changes to the windows requirements because I don't know what I have to do there and I can't test them.

The Dockerfile **is not working**.  For some reason even after installing firefox in the image, selenium refuses to use it. That has to be fixed before merging it.

### CODE REVIEW

**Comment by gntouts** [comment]
Thanks a lot for taking the time to solve this.
I was able to get the Dockerfile to work by install firefox-esr:

```
FROM python:3.9
EXPOSE 80
RUN /usr/local/bin/python -m pip install --upgrade pip

+ RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
+    DEBIAN_FRONTEND=noninteractive apt-get install -y firefox-esr

COPY ./src /src
WORKDIR "/src"
RUN pip install -r req/requirements.txt
CMD [ "uvicorn", "app:app", "--host", "0.0.0.0", "--port",  "80"]
```

The same applied to the "slim" Dockerfile:

```
FROM python:3.9.10-alpine

+ RUN apk add --update \
+    firefox-esr \ 
+    && rm -rf /var/cache/apk/*

COPY --from=base /svc /svc
```

I successfuly tracked an ACS voucher, using the `track` endpoint. 
However, the `track-all` endpoint returned `CourierNotSupportedError or InvalidTrackingNumber`, but that seems to be a separate issue.

**Comment by DanielPikilidis** [comment]
Oh nice. You can add the changes to that branch if you want and I'll look at that track-all error.

**Comment by DanielPikilidis** [comment]
I think the changes are ready to be merged.

**Comment by gntouts** [comment]
Thanks a lot!

**Pull request merged**
